config/routes.rb
Catalogs::Application.routes.draw do
  match "/auth/:provider/callback" => "authentications#create"
  resources :authentications
  get "signout" => "sessions#destroy", :as => "signout"
  
  resources :calls

  resources :boxes

  resources :publishers do
    resources :catalogs
    resources :calls
  end

  resources :catalogs do
    resources :boxes
  end

  get "home/index"

  root :to => "home#index"
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :publisher
  has_many :boxes
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
  # GET /catalogs
  # GET /catalogs.json
  def index
    @catalogs = current_user.catalogs.all

    respond_to do |format|
      format.html
    end
  end

  # GET /catalogs/1
  # GET /catalogs/1.json
  def show
    @catalog = current_user.catalogs.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # GET /catalogs/new
  # GET /catalogs/new.json
  def new
    @catalog = Catalog.new

    if params[:publisher_id]
      @catalog.publisher_id = params[:publisher_id]
    end

    respond_to do |format|
      format.html
    end
  end

  # GET /catalogs/1/edit
  def edit
    @catalog = current_user.catalogs.find(params[:id])
  end

  # POST /catalogs
  # POST /catalogs.json
  def create
    @catalog = Catalog.new(params[:catalog])
    
    publisher = current_user.publishers.find_by_id(@catalog.publisher_id)
    if publisher.nil?
      raise 'Publisher does not exist'
    end
    
    respond_to do |format|
      if @catalog.save
        format.html { redirect_to @catalog, :notice => 'Catalog was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /catalogs/1
  # PUT /catalogs/1.json
  def update
    @catalog = current_user.catalogs.find(params[:id])

    respond_to do |format|
      if @catalog.update_attributes(params[:catalog])
        format.html { redirect_to @catalog, :notice => 'Catalog was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /catalogs/1
  # DELETE /catalogs/1.json
  def destroy
    @catalog = current_user.catalogs.find(params[:id])
    @catalog.destroy

    respond_to do |format|
      format.html { redirect_to catalogs_url }
    end
  end
end

app/views/catalogs/_form.html.erb
<% if @catalog.publisher %>
  <p> for publisher <%= @catalog.publisher.name %>
<% end %>

<%= form_for(@catalog) do |f| %>
  <% if @catalog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@catalog.errors.count, "error") %> prohibited this catalog from being saved:</h2>

      <ul>
      <% @catalog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :publisher_id %>
  
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :issue %><br />
    <%= f.text_field :issue %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/catalogs/edit.html.erb
<h1>Editing catalog</h1>

<%= render 'form' %>

<%= link_to 'Show', @catalog %> |
<%= link_to 'Back', :back %>

app/views/catalogs/index.html.erb
<table>
  <tr>
    <th>Publisher</th>
    <th>Date</th>
    <th>Issue</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @catalogs.each do |catalog| %>
  <tr>
    <td><%= link_to catalog.publisher.name, publisher_path(catalog.publisher) %></td>
    <td><%= catalog.date %></td>
    <td><%= catalog.issue %></td>
    <td><%= link_to 'Show', catalog %></td>
    <td><%= link_to 'Edit', edit_catalog_path(catalog) %></td>
    <td><%= link_to 'Destroy', catalog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Catalog', new_catalog_path %>

app/views/catalogs/new.html.erb
<h1>New catalog</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/catalogs/show.html.erb
<p>
  <b>Publisher:</b>
  <%= link_to @catalog.publisher.name, publisher_path(@catalog.publisher) %>
</p>

<p>
  <b>Date:</b>
  <%= @catalog.date %>
</p>

<p>
  <b>Issue:</b>
  <%= @catalog.issue %>
</p>


<%= link_to 'Edit', edit_catalog_path(@catalog) %> |
<%= link_to 'Back', :back %>

<h3>Boxes</h3>
<table>
  <tr>
    <th>Label</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @catalog.boxes.each do |box| %>
  <tr>
    <td><%= box.label %></td>
    <td style="background-color: <%= box.color %>;"><%= box.value %></td>
    <td><%= link_to 'Show', box %></td>
    <td><%= link_to 'Edit', edit_box_path(box) %></td>
    <td><%= link_to 'Destroy', box, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to "New box", new_catalog_box_path(@catalog) %>