config/routes.rb
Catalogs::Application.routes.draw do
  match "/auth/:provider/callback" => "authentications#create"
  resources :authentications
  get "signout" => "sessions#destroy", :as => "signout"
  
  resources :calls

  resources :boxes

  resources :publishers do
    resources :catalogs
    resources :calls
  end

  resources :catalogs do
    resources :boxes
  end

  get "home/index"

  root :to => "home#index"
end

app/models/call.rb
class Call < ActiveRecord::Base
  belongs_to :publisher
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  # GET /calls
  # GET /calls.json
  def index
    @calls = current_user.calls.all

    respond_to do |format|
      format.html
    end
  end

  # GET /calls/1
  # GET /calls/1.json
  def show
    @call = current_user.calls.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  # GET /calls/new
  # GET /calls/new.json
  def new
    @call = Call.new

    if params[:publisher_id]
      @call.publisher_id = params[:publisher_id]
    end

    respond_to do |format|
      format.html
    end
  end

  # GET /calls/1/edit
  def edit
    @call = current_user.calls.find(params[:id])
  end

  # POST /calls
  # POST /calls.json
  def create
    @call = Call.new(params[:call])
    
    publisher = current_user.publishers.find_by_id(@call.publisher_id)
    if publisher.nil?
      raise 'publisher does not exist'
    end
    
    respond_to do |format|
      if @call.save
        format.html { redirect_to @call, :notice => 'Call was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /calls/1
  # PUT /calls/1.json
  def update
    @call = current_user.calls.find(params[:id])

    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to @call, :notice => 'Call was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /calls/1
  # DELETE /calls/1.json
  def destroy
    @call = current_user.calls.find(params[:id])
    @call.destroy

    respond_to do |format|
      format.html { redirect_to calls_url }
    end
  end
end

app/views/calls/_form.html.erb
<%= form_for(@call) do |f| %>
  <% if @call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
      <% @call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :publisher_id %>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :result %><br />
    <%= f.text_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calls/edit.html.erb
<h1>Editing call</h1>

<%= render 'form' %>

<%= link_to 'Show', @call %> |
<%= link_to 'Back', :back %>

app/views/calls/index.html.erb
<h1>Listing calls</h1>

<table>
  <tr>
    <th>Publisher</th>
    <th>Date</th>
    <th>Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @calls.each do |call| %>
  <tr>
    <td><%= call.publisher %></td>
    <td><%= call.date %></td>
    <td><%= call.result %></td>
    <td><%= link_to 'Show', call %></td>
    <td><%= link_to 'Edit', edit_call_path(call) %></td>
    <td><%= link_to 'Destroy', call, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call', new_call_path %>

app/views/calls/new.html.erb
<h1>New call</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/calls/show.html.erb
<p>
  <b>Publisher:</b>
  <%= link_to @call.publisher.name, publisher_path(@call.publisher) %>
</p>

<p>
  <b>Date:</b>
  <%= @call.date %>
</p>

<p>
  <b>Result:</b>
  <%= @call.result %>
</p>


<%= link_to 'Edit', edit_call_path(@call) %> |
<%= link_to 'Back', :back %>