config/routes.rb
Catalogs::Application.routes.draw do
  match "/auth/:provider/callback" => "authentications#create"
  resources :authentications
  get "signout" => "sessions#destroy", :as => "signout"
  
  resources :calls

  resources :boxes

  resources :publishers do
    resources :catalogs
    resources :calls
  end

  resources :catalogs do
    resources :boxes
  end

  get "home/index"

  root :to => "home#index"
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  belongs_to :user
  has_many :catalogs
  has_many :boxes, :through => :catalogs
  has_many :calls

  validates_format_of :phone, :with => /^\d{3}-\d{3}-\d{4}$/, :message => 'Must be in 000-000-0000 format'

  def self.search(search)
     if search
       if Rails.env.production?
         # differences between PG and SQLite suck
         find(:all, :conditions => ['name ILIKE ? OR phone LIKE ?', "%#{search}%", "%#{search}%"], :order => "should_call DESC")
       else
         find(:all, :conditions => ['name LIKE ? OR phone LIKE ?', "%#{search}%", "%#{search}%"], :order => "should_call DESC")
       end
     else
       find(:all, :order => "should_call DESC")
     end
  end

  def events
     (catalogs + calls).sort_by(&:date).reverse
  end

  def call_list
    find(:all, :conditions => { should_call => true }, :include => [:catalogs, :boxes])
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = current_user.publishers.search(params[:search])

    respond_to do |format|
      format.html
    end
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = current_user.publishers.find(params[:id], :include => [:catalogs, :calls])
    
    respond_to do |format|
      format.html
    end
  end

  # GET /publishers/new
  # GET /publishers/new.json
  def new
    @publisher = Publisher.new

    respond_to do |format|
      format.html
    end
  end

  # GET /publishers/1/edit
  def edit
    @publisher = current_user.publishers.find(params[:id])
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = current_user.publishers.new(params[:publisher])

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, :notice => 'Publisher was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /publishers/1
  # PUT /publishers/1.json
  def update
    @publisher = current_user.publishers.find(params[:id])

    respond_to do |format|
      if @publisher.update_attributes(params[:publisher])
        format.html { redirect_to @publisher, :notice => 'Publisher was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = current_user.publishers.find(params[:id])
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url }
    end
  end
end

app/views/publishers/_event_table.html.erb
<table>
  <tr>
    <th>Type</th>
    <th>Date</th>
    <th>Issue/Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% events.each do |event| %>
  <tr>
    <% if event.class == Call %>
    <td>Call</td>
    <td><%= event.date %></td>
    <td><%= event.result %></td>
    <td><%= link_to 'Edit', edit_call_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
    <% elsif event.class == Catalog %>
    <td><%= link_to 'Catalog', catalog_path(event) %></td>
    <td><%= event.date %></td>
    <td><%= event.issue %></td>
    <td><%= link_to 'Edit', edit_catalog_path(event) %></td>
    <td><%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :should_call %><br />
    <%= f.check_box :should_call %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', :back %>

app/views/publishers/index.html.erb
<h1>Listing publishers</h1>

<%= link_to 'New Publisher', new_publisher_path %>
<br />

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Should call</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @publishers.each do |publisher| %>
  <tr>
    <td><%= publisher.name %></td>
    <td style="white-space: nowrap"><% if publisher.phone %><a href="tel:<%= publisher.phone %>"><%= publisher.phone %></a><% end %></td>
    <td><%= publisher.should_call %></td>
    <td><%= publisher.address %></td>
    <td><%= link_to 'Show', publisher %></td>
    <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
    <td><%= link_to 'Destroy', publisher, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/publishers/show.html.erb
<h2>Publisher</h2>

<p>
  <b>Name:</b>
  <%= @publisher.name %>
</p>

<p>
  <b>Address:</b>
  <%= @publisher.address %>
</p>

<p>
  <b>Phone:</b>
  <% if @publisher.phone %><a href="tel:<%= @publisher.phone %>"><%= @publisher.phone %></a><% end %>
</p>

<p>
  <b>Should call:</b>
  <%= @publisher.should_call %>
</p>


<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', :back %>

<h2>Events</h2>
<%= link_to 'New Catalog', new_publisher_catalog_path(@publisher) %> <%= link_to 'New Call', new_publisher_call_path(@publisher) %>
<%= render :partial => "event_table", :locals => { :events => @publisher.events } %>