config/routes.rb
Catalogs::Application.routes.draw do
  match "/auth/:provider/callback" => "authentications#create"
  resources :authentications
  get "signout" => "sessions#destroy", :as => "signout"
  
  resources :calls

  resources :boxes

  resources :publishers do
    resources :catalogs
    resources :calls
  end

  resources :catalogs do
    resources :boxes
  end

  get "home/index"

  root :to => "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= content_for?(:title) ? yield(:title) : "Catalogs" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <small>Catalogs</small>
  <div id="user_nav">
    <% if current_user %>
      <%= link_to "Logins", authentications_path %>&nbsp;<%= link_to "Sign out", signout_path %>
    <% else %>
      <%= link_to "Sign in", authentications_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

  <% if current_user %>
    <div>
      <%= form_tag publishers_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>&nbsp;<%= submit_tag "Search publishers", :name => nil %>
        </p>
      <% end %>
    </div>
  <% end %>

  <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
<% if Rails.env.production? %>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-27641837-1']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<% end %>
</body>
</html>